### ISSUE TITLE
what to do to implement openssl cms verify function using the lib lua-resty-cms?

### ISSUE THREAD

**Issue by timusketeers** [toruneko/lua-resty-cms#1]
I want to implement the following command: **openssl cms -verify -in /tmp/content -certfile /tmp/cert.pem -CAfile /tmp/cacert.pem -inform PEM -nosmimecap -nodetach -nocerts -noattr**, how should I use the lib lua-resty-cms to implement this function? thanks

**Comment by toruneko** [comment]
the new `cms.lua` was pushed to master branch, based on openssl ver 1.1.0,
and upgraded to use high level functions (`CMS_encrypt`, `CMS_decrypt`, `CMS_sign`, `CMS_verify`).

such as:
```
int CMS_verify(CMS_ContentInfo *cms, struct stack_st_X509 *certs,
               X509_STORE *store, BIO *dcont, BIO *out, unsigned int flags);
```

If you want to add smimecap,nodetach,nocerts,noattr flags,  you should use under flags:
```
CMS_NOCERTS         0x2
CMS_DETACHED       0x40
CMS_NOATTR            0x100
CMS_NOSMIMECAP  0x200
```

**Comment by timusketeers** [comment]
Hi, below is some part of the code: 
function _M:verify(data)
    if not data then
      return nil, "no cihper data"
    end
    
    local cms, err = d2i_CMS_ContentInfo(data)
    if not cms then
        return nil, err
    end
   ...........
end

I pass the param data with the following string:
-----BEGIN CMS-----
MIIDfQYJKoZIhvcNAQcCoIIDbjCCA2oCAQExDTALBglghkgBZQMEAgEwggHLBgkq
hkiG9w0BBwGgggG8BIIBuHsidG9rZW4iOnsiZXhwaXJlc19hdCI6IjIwMTktMDUt
MDlUMDI6NTU6NDkuMTM4MDAwWiIsIm1ldGhvZHMiOlsicGFzc3dvcmQiXSwiY2F0
YWxvZyI6W10sImRvbWFpbiI6eyJuYW1lIjoib3Bfc2VydmljZSIsImlkIjoiNzFj
ZTY3MzE3NTAyNGQwNDk1NjY0ZTUyNWU1MmJhYzAifSwicm9sZXMiOlt7Im5hbWUi
OiJvcF9zZXJ2aWNlIiwiaWQiOiIwIn0seyJuYW1lIjoib3BfY3JlZCIsImlkIjoi
MCJ9XSwiaXNzdWVkX2F0IjoiMjAxOS0wNS0wOFQwMjo1NTo0OS4xMzgwMDBaIiwi
dXNlciI6eyJkb21haW4iOnsibmFtZSI6Im9wX3NlcnZpY2UiLCJpZCI6IjcxY2U2
NzMxNzUwMjRkMDQ5NTY2NGU1MjVlNTJiYWMwIn0sIm5hbWUiOiJjb25zb2xlX2Fk
bWluIiwicGFzc3dvcmRfZXhwaXJlc19hdCI6IiIsImlkIjoiOTFiNGMyMTM4ZGYy
NDM4YWE2MzVkZGIyOTEzYTMyYTgifX19MYIBhTCCAYECAQEwXDBXMQswCQYDVQQG
EwJVUzEOMAwGA1UECAwFVW5zZXQxDjAMBgNVBAcMBVVuc2V0MQ4wDAYDVQQKDAVV
bnNldDEYMBYGA1UEAwwPd3d3LmV4YW1wbGUuY29tAgEBMAsGCWCGSAFlAwQCATAN
BgkqhkiG9w0BAQEFAASCAQBhvqDc8x0vQ/kt1dmIcX+AEwOPHDXwZTaaerwo3hdY
1iXSCabNQ28FtuVxpTx5d0d1k2B3GJE69bXMI4Seq+/Q67Ish8M4sCJPWnOtcc3y
3w/Hl7HzWBay8KxAN9VChuygmZ1XR94P+kkt4uOmJNEZP34sVOs1U+Qh318uQoG8
DFc5x6iTIAyXdwpJ7yMukMN06SsukDxqanQqdmD7A+mI+YRr85M2TWDkQmz8kIps
PaxtkGaUsL2RYY0EdwHFK0fk2nLuA1lvIygbWAEIol0YmBS/DDl4E9nIW5pGwsNL
nAG4dKgoCf4TKrdXaNbftLWAfFNq0obX8GXcY9CM5tOS
-----END CMS-----

but get the error message of "wrong tag" from the function d2i_CMS_ContentInfo. It seems the content not a valid cms format content, but I tried use the openssl cms verify command, it works ok. Any ideas?

**Comment by timusketeers** [comment]
the string passed to the param data is 64 length each line

**Comment by toruneko** [comment]
Because of 
```
-----BEGIN CMS-----
.....
-----END CMS-----
```
is already a cms content info data.
so we should use `PEM_read_bio_CMS` functions to read.

```
ffi.cdef[[
...
CMS_ContentInfo *PEM_read_bio_CMS(BIO *bp, CMS_ContentInfo **a, pem_password_cb *cb, void *u);
...
]]

 local data_in, err = BIO_new(data)
 local cms = C.PEM_read_bio_CMS(data_in, ffi_null, ffi_null, password)
```

**Comment by toruneko** [comment]
```
local cms = require "resty.cms".new(...)
local cms_content_info, err = cms:PEM_read_bio_CMS(DATA,PASS)
if not cms_content_info then
    error(err)
end

local out,err = cms:CMS_verify(cms_content_info, FLAGS)
if not out then
    error(err)
end

local str, errr = cms:BIO_read(out)
if not str then
    error(err)
end
```

**Comment by timusketeers** [comment]
Thanks for your in-time reply. Follow your suggestion, I modified the code as show below:


    function _M:verify(data, ca_cert, sign_cert)
    if not data then
      return nil, "no cihper data"
    end

    local cms, err = PEM_read_bio_CMS(data)
    if not cms then
        return nil, err
    end

    local cacert, err = PEM_read_bio_X509(ca_cert, nil)
    if not cacert then
      return nil, err
    end
    
    local ca, error = X509_STORE_new(cacert)
    if not ca then
      return nil, error
    end
    
    local signcert, err = PEM_read_bio_X509(sign_cert, nil)
    if not signcert then
      return nil, err
    end
    
    local flags = bor(CMS_NOSMIMECAP, CMS_DETACHED, CMS_NOCERTS, CMS_NOATTR)
    local out = BIO_new()
    local certs = SKM_sk_new("struct stack_st_X509 *", {signcert})
    if 0 == C.CMS_verify(cms, certs, ca, ffi_null, out, flags) then
        return nil, get_error()
    end

    local verified, err = BIO_read(out)
    if not verified then
        return nil, err
    end
    return verified
    end

params values passsed to the function is:
1. data: (type is string)
-----BEGIN CMS-----
MIIDfQYJKoZIhvcNAQcCoIIDbjCCA2oCAQExDTALBglghkgBZQMEAgEwggHLBgkq
hkiG9w0BBwGgggG8BIIBuHsidG9rZW4iOnsiZXhwaXJlc19hdCI6IjIwMTktMDUt
MDlUMDI6NTU6NDkuMTM4MDAwWiIsIm1ldGhvZHMiOlsicGFzc3dvcmQiXSwiY2F0
YWxvZyI6W10sImRvbWFpbiI6eyJuYW1lIjoib3Bfc2VydmljZSIsImlkIjoiNzFj
ZTY3MzE3NTAyNGQwNDk1NjY0ZTUyNWU1MmJhYzAifSwicm9sZXMiOlt7Im5hbWUi
OiJvcF9zZXJ2aWNlIiwiaWQiOiIwIn0seyJuYW1lIjoib3BfY3JlZCIsImlkIjoi
MCJ9XSwiaXNzdWVkX2F0IjoiMjAxOS0wNS0wOFQwMjo1NTo0OS4xMzgwMDBaIiwi
dXNlciI6eyJkb21haW4iOnsibmFtZSI6Im9wX3NlcnZpY2UiLCJpZCI6IjcxY2U2
NzMxNzUwMjRkMDQ5NTY2NGU1MjVlNTJiYWMwIn0sIm5hbWUiOiJjb25zb2xlX2Fk
bWluIiwicGFzc3dvcmRfZXhwaXJlc19hdCI6IiIsImlkIjoiOTFiNGMyMTM4ZGYy
NDM4YWE2MzVkZGIyOTEzYTMyYTgifX19MYIBhTCCAYECAQEwXDBXMQswCQYDVQQG
EwJVUzEOMAwGA1UECAwFVW5zZXQxDjAMBgNVBAcMBVVuc2V0MQ4wDAYDVQQKDAVV
bnNldDEYMBYGA1UEAwwPd3d3LmV4YW1wbGUuY29tAgEBMAsGCWCGSAFlAwQCATAN
BgkqhkiG9w0BAQEFAASCAQBhvqDc8x0vQ/kt1dmIcX+AEwOPHDXwZTaaerwo3hdY
1iXSCabNQ28FtuVxpTx5d0d1k2B3GJE69bXMI4Seq+/Q67Ish8M4sCJPWnOtcc3y
3w/Hl7HzWBay8KxAN9VChuygmZ1XR94P+kkt4uOmJNEZP34sVOs1U+Qh318uQoG8
DFc5x6iTIAyXdwpJ7yMukMN06SsukDxqanQqdmD7A+mI+YRr85M2TWDkQmz8kIps
PaxtkGaUsL2RYY0EdwHFK0fk2nLuA1lvIygbWAEIol0YmBS/DDl4E9nIW5pGwsNL
nAG4dKgoCf4TKrdXaNbftLWAfFNq0obX8GXcY9CM5tOS
-----END CMS-----

2.ca_cert: (type is string)
-----BEGIN CERTIFICATE-----
MIIDgTCCAmmgAwIBAgIJAJMn9KUT02C3MA0GCSqGSIb3DQEBBQUAMFcxCzAJBgNV
BAYTAlVTMQ4wDAYDVQQIDAVVbnNldDEOMAwGA1UEBwwFVW5zZXQxDjAMBgNVBAoM
BVVuc2V0MRgwFgYDVQQDDA93d3cuZXhhbXBsZS5jb20wHhcNMTYwNjI5MDgxMDQ1
WhcNMTkwNjI5MDgxMDQ1WjBXMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVW5zZXQx
DjAMBgNVBAcMBVVuc2V0MQ4wDAYDVQQKDAVVbnNldDEYMBYGA1UEAwwPd3d3LmV4
YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1a1FrNgJ
pU+ryGNk2W1beCq0ibDfU7XFWk+bcycXW9FBp46Z4BZ+ipbLKXNARE+1aeFI/yRO
mUznB4h35JpLNqXR/q0hZ9wJqci5w6lc0zVKSUwpSdh1Zcy6Eezw/h5SqxJCuksw
TfyO9OX3o//AMGuI2SBUBer8vRC/v3aBxYRUFnVaxa0tE3jR+hy93tHQQTKaPm6k
GytD8USR43ySH8qfaZMupWYddrOTfCe/7yBJmlWvPHI8sbXPf9G/v6dPhjThnMw7
53GgPIJK+pypkHt/X0haAtbUf8dqOcft6YYIuRvGQPw7ISgjWLnCD8sMc44Egc4/
HFGV1WgI/ms9ywIDAQABo1AwTjAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBTVft4R
qoDZna+qVBq8pdIF5SJUqjAfBgNVHSMEGDAWgBTVft4RqoDZna+qVBq8pdIF5SJU
qjANBgkqhkiG9w0BAQUFAAOCAQEA0VbcZi/Xnjn8ukCCSLZIdf2vMwd7DnUIMvaO
ihfoh0p2EeQh80PysBUzL4zCeLQAOCRoEUaihuyuLwjw+OFL8yiSENEqTl8DcoAH
mc2AyGVRnXrhY+mGh8k+p+P0h694o2BZHbex9+f6R4EQrrHJSvf2rj3hOQDPDY1I
hty1twWST2fr2Wib2PaqoQeSHnrx+U1NZOaw5txCbQ11iou2SH8kRAhTEL0OqITn
PFxoWUSPHUYHBUn5ukIACdyDKO/vgS2NJjycMuzc4iFUsg5zdzLPcJDbsGHcQsnu
/wRHqU0czBbpSiCGyNhl2c9B1Eoj7JPUE7xhJXOQbqecmBGI9g==
-----END CERTIFICATE-----

3. sign_cert: (type is string)
-----BEGIN CERTIFICATE-----
MIIDZjCCAk6gAwIBAgIBATANBgkqhkiG9w0BAQUFADBXMQswCQYDVQQGEwJVUzEO
MAwGA1UECAwFVW5zZXQxDjAMBgNVBAcMBVVuc2V0MQ4wDAYDVQQKDAVVbnNldDEY
MBYGA1UEAwwPd3d3LmV4YW1wbGUuY29tMB4XDTE2MDYyOTA4MTA0NVoXDTE5MDYy
OTA4MTA0NVowRzELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVuc2V0MQ4wDAYDVQQK
DAVVbnNldDEYMBYGA1UEAwwPd3d3LmV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAsKAkDmY8MN7DAHHpUA+WTSSfzegFruxs80XY3SHP
FSYa8dNoH3E+5ZDUBLtm0KLHdrbj2jZbGwHfowV/tNl96sSFUFPGC62W8kiqkNKY
qjl9YZjc7uRSJva5PE2hKJGiIPMdKfuAcSlB6zzO0gcUFOg3ZSeF+9rZ0EVl08uY
DufSyb0nD1g9FAmcTx5aPKyMaFBY8Y2VDJ6peWlMpl5B209WAVMQrxhw0T6cXQ4j
Sn0qjBSvJE2cpeJKxHfhrfk25ayuqxUiYg3kSCK/2iTvKyB3pIbCooG4L5fGGH4t
aF8uCVzGgWbYNpJZcQqciAHG4/BgBgQnSmkwLq4I5x6/qwIDAQABo00wSzAJBgNV
HRMEAjAAMB0GA1UdDgQWBBR85jXxYeZLw9iG/VVpo/3BfKujHDAfBgNVHSMEGDAW
gBTVft4RqoDZna+qVBq8pdIF5SJUqjANBgkqhkiG9w0BAQUFAAOCAQEAyOtiDx2i
xolKVYgE+xAabzXmvLWejF5GNj0x5x5UP3KxRY6MuyY5+YsJ5EYnXx+J6Gvm11nu
Tynsb1eqZgKTlw+tN0Cn1hvQtvfjH2NpOJdsTB6PAy0iu0uqxX4YGyyDTC/9Vm1j
8wL+3g2fZb26HzQmmlDuSFXCx4KPbxWKRBnWPmagXn3QIAfXhjQo8w2BlObG97Tw
ACaozaf3VweoQ/2ohFdTAURJp5TKiTAYEmXljvDmh2xnT8XGz5rsi3SHlp1Zfy49
Bzvbc0S4ZfqGdWhc+/x9uoQVa1KfpPf7TtqCit0f2XYs1sj7EwKJ2InUf02205Qw
Ht9/EYeOszXLmQ==
-----END CERTIFICATE-----

when I execute the function verify(data, ca_cert, sign_cert), the following error occur:

ERROR: ...oud/openresty/luajit/share/lua/5.1/wakanda/tools/cms.lua:285: /opt/cloud/openresty/luajit/lib/libluajit-5.1.so.2: undefined symbol: CMS_verify

I viewed the file /usr/lib64/libcrypto.so.10 on my PC and find the CMS_verify string in it. any suggestion, thanks

**Comment by timusketeers** [comment]
append info:

I confirm that the following code is added in the code mentioned above:
ffi.cdef[[
...
int CMS_verify(CMS_ContentInfo *cms, struct stack_st_X509 *certs, X509_STORE *store, BIO *dcont, BIO *out, unsigned int flags);
...
]]

**Comment by timusketeers** [comment]
the whole code is show below:

**Comment by timusketeers** [comment]
the whole code is show below:
```
local bit = require "bit"
local ffi = require "ffi"
local ffi_new = ffi.new
local ffi_cast = ffi.cast
local ffi_gc = ffi.gc
local ffi_str = ffi.string
local ffi_null = ffi.null
local C = ffi.C
local bor = bit.bor
local band = bit.band
local setmetatable = setmetatable
local tonumber = tonumber
local type = type
local ipairs = ipairs

local BIO_TYPE_MEM = bor(1, 0x0400)
local BIO_CTRL_INFO = 3
local BIO_CTRL_PENDING = 10
local BIO_CTRL_FLUSH = 11

local NID_pkcs7_enveloped = 23
local CMS_TEXT = 0x1

local CMS_NOCERTS               =  0x2
local CMS_NOSMIMECAP            =  0x200
local CMS_NO_CONTENT_VERIFY     =  0x4
local CMS_NO_ATTR_VERIFY        =  0x8
local CMS_NO_SIGNER_CERT_VERIFY =  0x20
local CMS_DETACHED              =  0x40
local CMS_NOATTR                =  0x100
local CMS_STREAM                = 0x1000
local CMS_NOCRL                 = 0x2000
local CMS_PARTIAL               = 0x4000
local CMS_DEBUG_DECRYPT         = 0x20000

local CMS_RECIPINFO_NONE = -1
local CMS_RECIPINFO_TRANS = 0
local CMS_RECIPINFO_AGREE = 1
local CMS_RECIPINFO_KEK = 2
local CMS_RECIPINFO_PASS = 3
local CMS_RECIPINFO_OTHER = 4

local _M = { _VERSION = '0.01' }
local mt = { __index = _M }

ffi.cdef [[
//ERR Functions
unsigned long ERR_get_error(void);
const char *ERR_reason_error_string(unsigned long e);
void ERR_clear_error(void);

// BIO Functions
typedef struct bio_st BIO;
typedef struct bio_method_st BIO_METHOD;
BIO_METHOD *BIO_s_mem(void);
BIO * BIO_new(BIO_METHOD *type);
void BIO_vfree(BIO *a);
int BIO_puts(BIO *bp,const char *buf);
int BIO_read(BIO *b, void *data, int len);
long BIO_ctrl(BIO *bp, int cmd, long larg, void *parg);

//stack Functions
typedef struct stack_st OPENSSL_STACK;
OPENSSL_STACK *OPENSSL_sk_new_null(void);
void OPENSSL_sk_free(OPENSSL_STACK *st);
int OPENSSL_sk_push(OPENSSL_STACK *st, void *data);

//stack Functions
typedef struct stack_st _STACK;
_STACK *sk_new_null(void);
void sk_free(_STACK *st);
int sk_push(_STACK *st, void *data);
void sk_pop_free(_STACK *st, void (*func) (void *));

//cipher Functions
typedef struct evp_cipher_st EVP_CIPHER;
const EVP_CIPHER *EVP_des_ede(void);
const EVP_CIPHER *EVP_des_cbc(void);
const EVP_CIPHER *EVP_des_ede3_cbc(void);

//RSA Functions
typedef int pem_password_cb(char *buf, int size, int rwflag, void *userdata);
typedef struct rsa_st RSA;
void RSA_free(RSA *rsa);
RSA * PEM_read_bio_RSAPrivateKey(BIO *bp, RSA **rsa, pem_password_cb *cb, void *u);

//X509 Functions
typedef struct x509_st X509;
typedef struct x509_store_st X509_STORE;
X509 *PEM_read_bio_X509(BIO *bp, X509 **x, pem_password_cb *cb, void *u);
void X509_free(X509 *x509);
X509_STORE *X509_STORE_new(void);
void X509_STORE_free(X509_STORE *v);
int X509_STORE_add_cert(X509_STORE *ctx, X509 *x);

//PKEY Functions
typedef struct evp_pkey_st EVP_PKEY;
EVP_PKEY *EVP_PKEY_new(void);
void EVP_PKEY_free(EVP_PKEY *key);
int EVP_PKEY_set1_RSA(EVP_PKEY *pkey,RSA *key);

//CMS Functions
typedef struct CMS_ContentInfo_st CMS_ContentInfo;
CMS_ContentInfo *CMS_ContentInfo_new();
void *CMS_ContentInfo_free(CMS_ContentInfo *cms);
CMS_ContentInfo *PEM_read_bio_CMS(BIO *bp, CMS_ContentInfo **a, pem_password_cb *cb, void *u);
int CMS_verify(CMS_ContentInfo *cms, struct stack_st_X509 *certs, X509_STORE *store, BIO *dcont, BIO *out, unsigned int flags);
               
]]

local function get_error()
    local code = C.ERR_get_error()

    if code == 0 then
        return nil
    end

    local err = C.ERR_reason_error_string(code)

    return ffi_str(err)
end

local function BIO_new(data, method)
    if not method then
        method = C.BIO_s_mem()
    end

    local bio = C.BIO_new(method)
    if bio == ffi_null then
        return nil, get_error()
    end
    ffi_gc(bio, C.BIO_vfree)

    if data then
        local len = C.BIO_puts(bio, data)
        if len < 0 then
            return nil, get_error()
        end
    end
    return bio
end

local function BIO_read(bio)
    local len = C.BIO_ctrl(bio, BIO_CTRL_PENDING, 0, ffi_null)
    if len <= 0 then
        return nil, get_error()
    end

    local str = ffi_new("char[?]", len + 1)
    if C.BIO_read(bio, str, len) <= 0 then
        return nil, get_error()
    end
    str[len] = 0

    return ffi_str(str)
end

local function PEM_read_bio_X509(cert, pass)
    local bio, msg = BIO_new(cert)
    if not bio then
        return nil, msg
    end

    local x509 = C.PEM_read_bio_X509(bio, ffi_null, ffi_null, pass)
    if x509 == ffi_null then
        return nil, get_error()
    end
    ffi_gc(x509, C.X509_free)

    return x509
end

local function PEM_read_bio_CMS(data)
    local bio, msg = BIO_new(data)
    if not bio then
        return nil, msg
    end

    local cms = C.PEM_read_bio_CMS(bio, ffi_null, ffi_null, ffi_null)
    if cms == ffi_null then
        return nil, get_error()
    end
    ffi_gc(cms, C.CMS_ContentInfo_free)

    return cms
end

local function X509_STORE_new(cert)
    if not cert then
        return nil, "no cert"
    end

    local ctx = C.X509_STORE_new()
    if ctx == ffi_null then
        return nil, get_error()
    end
    ffi_gc(ctx, C.X509_STORE_free)

    if type(cert) ~= "table" then
        cert = { cert }
    end
    for _, x509 in ipairs(cert) do
        if C.X509_STORE_add_cert(ctx, x509) == 0 then
            return nil, get_error()
        end
    end

    return ctx
end

local function SKM_sk_new(typeof, data)
    if not data and type(data) ~= "table" then
        return nil
    end

    local stack = C.sk_new_null()
    if stack ~= ffi_null then
        ffi_gc(stack, C.sk_free)
    end

    for _, item in ipairs(data) do
        C.sk_push(stack, item)
    end

    if typeof then
        return ffi_cast(typeof, ffi_cast("intptr_t", stack))
    end
    return stack
end

local function sk_X509_new(certs)
    if not certs and type(certs) ~= "table" then
        return nil
    end

    local stack = C.OPENSSL_sk_new_null()
    if stack == ffi_null then
        return nil, get_error()
    end
    ffi_gc(stack, C.OPENSSL_sk_free)

    for _, cert in ipairs(certs) do
        C.OPENSSL_sk_push(stack, cert)
    end

    return ffi_cast("struct stack_st_X509 *", ffi_cast("intptr_t", stack))
end


function _M:new(opts)
  local tab = {}
  return setmetatable(tab, mt)
end

function _M:verify(data, ca_cert, sign_cert)
    if not data then
      return nil, "no cihper data"
    end
    
    local cms, err = PEM_read_bio_CMS(data)
    if not cms then
        return nil, err
    end
    
    local cacert, err = PEM_read_bio_X509(ca_cert, nil)
    if not cacert then
      return nil, err
    end
    
    local ca, error = X509_STORE_new(cacert)
    if not ca then
      return nil, error
    end
    
    local signcert, err = PEM_read_bio_X509(sign_cert, nil)
    if not signcert then
      return nil, err
    end
    
    local flags = bor(CMS_NOSMIMECAP, CMS_DETACHED, CMS_NOCERTS, CMS_NOATTR)
    local out = BIO_new()
    local certs = SKM_sk_new("struct stack_st_X509 *", {signcert})
    if 0 == C.CMS_verify(cms, certs, ca, ffi_null, out, flags) then
        return nil, get_error()
    end

    local verified, err = BIO_read(out)
    if not verified then
        return nil, err
    end

    return verified
end

return _M
```

**Comment by toruneko** [comment]
`CMS_verify` can be declared in Lua FFI based on openssl 1.1.0,
but openssl 1.0.2 does not support.
please check your openssl version is 1.1.0 or not.
